properties([
    parameters([
        [
            $class: 'ChoiceParameter',
            choiceType: 'PT_SINGLE_SELECT',
            name: 'ENVIRONMENT',
            description: 'Выберите окружение',
            filterLength: 1,
            filterable: false,
            script: [
                $class: 'GroovyScript',
                script: [
                    classpath: [],
                    sandbox: true,
                    script: '''
                        return ["dev", "prod", "stage"]
                    '''
                ]
            ]
        ],
        [
            $class: 'CascadeChoiceParameter',
            name: 'SERVICE',
            description: 'Выберите сервис',
            referencedParameters: 'ENVIRONMENT',
            script: [
                $class: 'GroovyScript',
                script: [
                    classpath: [],
                    sandbox: true,
                    script: '''
                        if (ENVIRONMENT == "dev") {
                            return ["frontend-dev", "backend-dev", "db-dev"]
                        } else if (ENVIRONMENT == "prod") {
                            return ["frontend-prod", "backend-prod", "db-prod"]
                        } else {
                            return ["frontend-stage", "backend-stage"]
                        }
                    '''
                ]
            ]
        ]
    ])
])

pipeline {
    agent any
    stages {
        stage('Run') {
            steps {
                echo "Выбрано окружение: ${params.ENVIRONMENT}"
                echo "Выбран сервис: ${params.SERVICE}"
            }
        }
    }
}