pipeline {
    agent any
    parameters {
        choice(name: 'TRIGGER_TYPE', choices: ['None', 'Cron', 'Webhook', 'Manual'], description: 'Выберите тип триггера')
        // Динамический параметр будет добавлен через Active Choices
    }
    stages {
        stage('Initialize') {
            steps {
                script {
                def triggerType = binding.variables.get("TRIGGER_TYPE") ?: "None"
                def options = []
                switch (triggerType) {
                    case "Cron":
                        options = ["Every Minute", "Every Hour", "Daily"]
                        break
                    case "Webhook":
                        options = ["GitHub", "Bitbucket", "Custom"]
                        break
                    case "Manual":
                        options = ["Run Now", "Schedule Later"]
                        break
                    default:
                        options = ["No Details Available"]
                }
                return options
                }
            }
        }
        stage('Run Job') {
            steps {
                echo "Запуск задачи с параметрами..."
                // Здесь можно добавить шаги в зависимости от параметров
            }
        }
    }
}