pipeline {
    agent {
        label "${params.jenkinsAgent}"
    }
    environment {
        IMAGE_NAME = "1c-java-vanessa"
        TAG = "latest"
    }
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    bat "docker build -t ${env.IMAGE_NAME}:${env.TAG} -f Docker\\Dockerfile ."
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    def containerName = "1c_env"
                    bat "docker run -it --name ${containerName} -d ${env.IMAGE_NAME}:${env.TAG}"
                }
            }
        }
    }
}