pipeline {
    agent {
        label "${params.jenkinsAgent}"
    }
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    def imageName = "1c-java-vanessa"
                    def tag = "latest"

                    // Используем 'bat' для Windows команд
                    bat "docker build -t ${imageName}:${tag} Docker\\Dockerfile ."
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    def containerName = "1c_env"

                    // Используем 'bat' для Windows команд
                    bat "docker run --name ${containerName} -d ${imageName}:${tag}"
                }
            }
        }
    }
}