pipeline {
    agent any
    parameters {
        string(name: 'Product', defaultValue: 'finessCorp', description: 'Product type')
        string(name: 'version', defaultValue: '4.0.51.1', description: 'Version number')
    }
    stages {
        stage('Get Presigned URL from 1C API') {
            steps {
                script {
                    // Определение applicationId на основе params.Product
                    def prod
                    if (params.Product.contains('finessCorp')) {
                        prod = "ff8080818114016801822509d75d0029"
                    } else if (params.Product.contains('salon30')) {
                        prod = "ff8080817ccbb453017d0ee91ffe000d"
                    } else if (params.Product.contains('SpaSalon3')) {
                        prod = "ff808081811401680182257b91c0002d"
                    } else {
                        error "Unknown Product type: ${params.Product}"
                    }

                    // Форматирование текущей даты
                    def currentDateTime = new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS").format(new Date())

                    // Формирование URL с query-параметрами для GET
                    def url = "https://1capp.link.1c.ru/1capp-ecw-admin/hs/ECWConfPublication/v1/getPresignedUrl"
                    url += "applicationId=${prod}&"
                    url += "name=${params.version}&"
                    url += "filename=1Cv8.dt&"
                    url += "releaseDate=${currentDateTime}"

                    // Вывод URL для отладки
                    echo "Request URL: ${url}"

                    try {
                        def presignedUrlResponse = httpRequest(
                            url: url,
                            httpMode: 'GET', // Возвращаемся к GET
                            contentType: 'APPLICATION_JSON',
                            customHeaders: [[name: 'Authorization', value: 'Basic bGFicG86ZEU5c2V6eWc=']],
                            validResponseCodes: '200:299',
                            ignoreSslErrors: true
                        )
                        echo "Get Presigned URL Response Status: ${presignedUrlResponse.status}"
                        echo "Get Presigned URL Response Content: ${presignedUrlResponse.content}"
                    } catch (Exception e) {
                        echo "Request failed with error: ${e.getMessage()}"
                        // Удаляем попытку доступа к e.response, так как оно недоступно
                        error "Failed to get presigned URL: ${e.getMessage()}"
                    }
                }
            }
        }
    }
}