pipeline {
    agent {
        label "${params.jenkinsAgent}"
    }
    environment {
        VRUNNER_PATH = 'vrunner' // Путь к исполняемому файлу Vanessa Runner
        allureResultsDir = "${env.WORKSPACE.replace('\\', '\\\\')}\\\\results"
        allureReportUrl = "${env.JENKINS_URL}job/${env.JOB_NAME.replaceAll('/', '/job/')}/${env.BUILD_NUMBER}/allure"
        cfsrc = "D:\\cf\\cf.cf"
    } 
    stages {
        stage('Инициализация параметров'){
            steps{
                script{
                    // Установка значений переменных
                    if (params.NameBaseRelease.contains('FitnessRel')) {
                        env.nameBaseUserRelease = "Администратор"
                        env.namefeature =  "fitness"
                        env.releaseRepository = "http://192.168.2.16/hran1c/repository.1ccr/fitness_release"
                    } else if (params.NameBaseRelease.contains('StomaRel')) {
                        env.nameBaseUserRelease = "admin"
                        env.namefeature = "stoma"
                        env.releaseRepository = "http://192.168.2.16/hran1c/repository.1ccr/stomatology2_release"
                    } else if (params.NameBaseRelease.contains('SalonRel')) {
                        env.nameBaseUserRelease = "Администратор"
                        env.namefeature = "salon"
                        env.releaseRepository = "http://192.168.2.16/hran1c/repository.1ccr/salon_release"
                    }
                }
            }
        }
        stage('Обновление в релизном хранилище'){
            steps{
                script{
                    bat """
                    chcp 65001
                    @call ${VRUNNER_PATH} session kill --with-nolock --db ${params.NameBaseRelease} --db-user ${env.nameBaseUserRelease}
                    @call ${VRUNNER_PATH} loadrepo --storage-name ${releaseRepository} --storage-user МихаилБ --storage-pwd 3AqH649z0B --ibconnection /Slocalhost/${params.NameBaseRelease} --db-user ${env.nameBaseUserRelease}
                    @call ${VRUNNER_PATH} updatedb --ibconnection /Slocalhost/${params.NameBaseRelease} --db-user ${env.nameBaseUserRelease}
                    """
                }
            }
        }
        stage('Выгрузка .cf и создание пустой базы') {
            parallel {
                stage('Выгрузка .cf файла конфигурации из ИБ') {
                    steps {
                        script {
                            bat """
                            chcp 65001
                            @call ${VRUNNER_PATH} unload ${cfsrc} --ibconnection /Slocalhost/${params.NameBaseRelease} --db-user ${env.nameBaseUserRelease}
                            """
                        }
                    }
                }
                stage('Создание пустой базы') {
                    steps {
                        script {
                            bat """
                            chcp 65001
                            @call ${VRUNNER_PATH} create --db-server localhost --name udd --dbms PostgreSQL --db-admin postgres --db-admin-pwd postgres
                            """
                        }
                    }
                }
            }
        }
        stage('Загрузка .cf файла в базу'){
            steps{
                script{
                    bat """
                    chcp 65001
                    @call ${VRUNNER_PATH} load --src ${cfsrc} --ibconnection /Slocalhost/udd
                    @call ${VRUNNER_PATH} updatedb --ibconnection /Slocalhost/udd
                    """
                }
            }
        }
        stage('Первоначальное заполнение'){
            steps{
                script{
                    bat """
                    chcp 65001
                    @call ${VRUNNER_PATH} vanessa --path vanessa-runner\\feature\\${env.namefeature}.feature --pathvanessa "C:\\VA_test\\vanessa-automation\\vanessa-automation.epf" --ibconnection /Slocalhost/pusto --vanessasettings vanessa-runner\\UpdatingdDemoDatabase\\VAParams.json
                    """
                }
            }
        }
        stage('Удаление созданной базы'){
            steps{
                script{
                    bat """
                    chcp 65001
                    @call ${VRUNNER_PATH} session kill --with-nolock --db udd --db-user admin
                    @call ${VRUNNER_PATH} remove --name udd --drop-database --clear-database --db-user admin
                    """
                }
            }
        }
    }
    post {
            always {
                script {
                     allure([
                        includeProperties: false,
                        jdk: '',
                        results: [[path: "results"]]
                    ])
                    def reportMessage = """
Тестирование первоначального заполнения: ${params.NameBaseRelease}
Allure отчет доступен по ссылке:
${allureReportUrl}
                        """
                        httpRequest(url: "https://api.telegram.org/bot${env.botToken}/sendMessage?chat_id=${env.chatId}&text=${URLEncoder.encode(reportMessage.trim(), 'UTF-8')}")
            }
        }
    }
}

